methods: avoid compilation error with GCC 13
http.cc:1014:18: error: ignoring return value of 'const _CharT* std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::c_str() const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]', declared with attribute 'nodiscard' [-Werror=unused-result]
 1014 |    FailFile.c_str();   // Make sure we dont do a malloc in the signal handler
      |    ~~~~~~~~~~~~~~^~
In file included from /usr/include/c++/13/string:54,
                 from ../include/apt-pkg/fileutl.h:23,
                 from http.cc:29:
/usr/include/c++/13/bits/basic_string.h:2594:7: note: declared here
 2594 |       c_str() const _GLIBCXX_NOEXCEPT
      |       ^~~~~
cc1plus: all warnings being treated as errors
make[1]: *** [Makefile:622: http.o] Error 1

Similarly in ftp.cc and rsh.cc

[imz: avoid C-style cast in favor of the less permissive static_cast,
so that the maintainer only has to pay attention to other risky casts.]