DynamicMMap(): fix extending WorkSpace to the real file size beyond requested
The error in code was due to the class member being shadowed by the
parameter. (To mitigate the possibility of such erroneous assignments,
I'll mark parameters read-only.)

Also commented on the purpose of iSize and WorkSpace member variables
in code in order to better understand what is going on.

(The shadowing error could be detected among all the compiler warnings
with -Wshadow:

    contrib/mmap.cc: In constructor 'DynamicMMap::DynamicMMap(FileFd&, long unsigned int, long unsigned int)':
    contrib/mmap.cc:164:1: error: declaration of 'WorkSpace' shadows a member of 'DynamicMMap' [-Werror=shadow]
      164 | }
          | ^
    In file included from contrib/mmap.cc:26:
    ../include/apt-pkg/mmap.h:82:18: note: shadowed declaration is here
       82 |    unsigned long WorkSpace;
          |                  ^~~~~~~~~

but there are too many of such errors for these warnings to be useful
for detecting errors, because it's the common style in APT source code
to name the constructor parameters same as class members.

One more possibility to mitigate the possibility of such errors with
the help of the compiler would be to declare the parameters const to
prevent them being uselessly assigned some values in the body in the
cases where it is actually meant to assign values to class members.)