apt-rpm: contrib/mmap.cc: avoid compilation error with GCC 13
contrib/mmap.cc:80:20: error: 'SIZE_MAX' was not declared in this scope
   80 |    if (EndOfFile > SIZE_MAX)
      |                    ^~~~~~~~
contrib/mmap.cc:38:8: note: 'SIZE_MAX' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   37 | #include <cassert>
  +++ |+#include <cstdint>
   38 |                                                                         /*}}}*/
contrib/mmap.cc:82:40: error: 'uintmax_t' does not name a type
   82 |                            static_cast<uintmax_t>(EndOfFile));
      |                                        ^~~~~~~~~
contrib/mmap.cc: In member function 'std::optional<long unsigned int> DynamicMMap::WriteString(const char*, size_t)':
contrib/mmap.cc:363:15: error: 'SIZE_MAX' was not declared in this scope
  363 |    if (Len == SIZE_MAX)
      |               ^~~~~~~~
contrib/mmap.cc:363:15: note: 'SIZE_MAX' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
make[1]: *** [Makefile:775: contrib/mmap.lo] Error 1

SIZE_MAX is defined in cstdint.h, include it.