apt-pkg/repository.h: fix typo in a header guard found by gcc 15 (-Werror=header-guard)
The typo was introduced in:

c27ced7a9 (Merging apt-rpm 0.5.5cnc1 over upstream APT in development trunk., 2003-02-03)

Recent GCC warns on this, which is treated as error:

In file included from acquire-item.cc:25:
../include/apt-pkg/repository.h:3: error: header guard 'PKGLIB_REPOSITORY_H' followed by '#define' of a different macro [-Werror=header-guard]
    3 | #ifndef PKGLIB_REPOSITORY_H
../include/apt-pkg/repository.h:4: note: 'PKBLIB_REPOSITORY_H' is defined here; did you mean 'PKGLIB_REPOSITORY_H'?
    4 | #define PKBLIB_REPOSITORY_H
cc1plus: all warnings being treated as errors